application: obcspiritualgifts
version: 3
runtime: python27
api_version: 1
threadsafe: false

#--------------INCLUDES--------------#
#includes:
#- includes.yaml
#--------------Handlers--------------#   
handlers:
#--------------Scripts---------------# 
- url: /
  script: src/sgtest.py
- url: /FTtest
  script: src/FT_client.py
- url: /config
  script: src/config.py
- url: /OAuth2
  script: src/OAuth2_Handler.py
- url: /.*
  script: /AppMain.py

#-------------LIBRARIES--------------#  

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: 2.6