application: obcspiritualgifts
version: 3
runtime: python27
api_version: 1
threadsafe: false

#--------------Handlers--------------#   
handlers:
#--------------Scripts---------------# 
- url: /static
  static_dir: static
- url: /.*
  script: src/sgtest.py

#-------------LIBRARIES--------------#  

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: 2.6