application: obcspiritualgifts
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /.*
  script: FT_Client.py

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest